{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hillr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hillR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hillR/hillR_{{ version }}.tar.gz
  sha256: ec15c4eec265812b8d91ca93694d9ba06e7f4c3836be26351a7709bb72f4843d

build:
  # skipping windows build due to no windows build for r-geiger dependency
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fd
    - r-ade4
    - r-ape
    - r-geiger
    - r-plyr
    - r-tibble
  run:
    - r-base
    - r-fd
    - r-ade4
    - r-ape
    - r-geiger
    - r-plyr
    - r-tibble

test:
  commands:
    - $R -e "library('hillR')"           # [not win]
    - "\"%R%\" -e \"library('hillR')\""  # [win]

about:
  home: https://github.com/daijiang/hillR
  license: MIT
  summary: Calculate taxonomic, functional and phylogenetic diversity measures through Hill Numbers proposed by Chao, Chiu and Jost (2014) <doi:10.1146/annurev-ecolsys-120213-091540>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
